spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
      # schema-locations: classpath:schema.sql
      # data-locations: classpath:data.sql

  datasource:
    hikari:
      initialization-fail-timeout: 60000
    url: jdbc:mysql://db:3306/shima_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
    username: appuser
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
